#!/bin/sh

sudo echo ""
echo "********************************************************************************"
echo "***                  --------------------------------------                  ***"
echo "***                  \033[1;5m             AIRLIGHT v0.1                           \033[0m   ***"
echo "***                  --------------------------------------                  ***"
echo "***                    requiere aircrack-ng and macchange                    ***"
echo "********************************************************************************"
echo ""
echo "       ║  [\033[36m01\033[0m]     \033[36mairmon-ng (configuration de la carte en mode monitoring)\033[0m"
echo "       ║  [\033[36m02\033[0m]     \033[36mifconfig (changer d'adresse MAC)\033[0m"
echo "       ║  [\033[36m03\033[0m]     \033[36mairodump-ng (trouver des réseaux)\033[0m"
echo "       ║"
echo "       ║  [\033[36m04\033[0m]     \033[36maireplay-ng (attaque par déauthentification)\033[0m"
echo "       ║  [\033[36m05\033[0m]     \033[36maircrack-ng (chiffrement WPA/WPA2)\033[0m"
echo "       ║"
echo "       ║  [\033[36m06\033[0m]     \033[36mHelp\033[0m"
echo "       ║  [\033[36m07\033[0m]     \033[36mInstall/Reinstall Aircrack-ng, Macchange\033[0m"
echo "       ║  [\033[36m08\033[0m]     \033[36mExit\033[0m"
echo "       ║  "
read -p "       ╚═══► " prog

if [ $prog -eq 01 ] ; then
	echo ""
	echo "\033[33m$ iwconfig\033[0m"
	echo ""
	iwconfig
	read -p "Interface : " interface
	echo $interface > /home/$USER/AirLight-master/logs/interface.txt
	sleep 1
	gnome-terminal -e "airlight"
	echo ""
	echo "\033[33m$ airmon-ng start $interface\033[0m"
	sudo airmon-ng start $interface
	sleep 4
	echo ""
	echo "\033[33m$ airodump-ng --encrypt wpa $interface\033[0m"
	sudo airodump-ng --encrypt wpa $interface
elif [ $prog -eq 02 ] ;  then
	echo ""
	echo "\033[33m$ ifconfig\033[0m"
	echo ""
	ifconfig
	read -p "Interface : " intermacdown
	echo ""
	echo "\033[33m$ ifconfig $intermacdown down\033[0m"
	echo ""
	sudo ifconfig $intermacdown down
	echo ""
	echo "\033[33m$ ifconfig\033[0m"
	echo ""
	ifconfig
	echo "\033[33m$ macchanger -a $intermacdown\033[0m"
	echo ""
	sudo macchanger -a $intermacdown
	echo ""
	sleep 4
	echo "\033[33m$ ifconfig\033[0m"
	echo ""
	ifconfig
	echo "\033[33m$ ifconfig $intermacdown up\033[0m"
	sudo ifconfig $intermacdown up
	ScriptLoc=$(readlink -f "$0")
	exec "$ScriptLoc"
elif [ $prog -eq 03 ] ; then
	echo ""
	interface=$(cat /home/$USER/AirLight-master/logs/interface.txt)
	echo "Interface : "$interface
	read -p "BSSID : " bssid
	echo $bssid > /home/$USER/AirLight-master/logs/bssid.txt
	read -p "CH : " ch
	echo $ch > /home/$USER/AirLight-master/logs/ch.txt
	sleep 2
	echo ""
	echo "\033[33m$ airodump-ng -w out --encrypt wpa -c $ch --bssid $bssid $interface\033[0m"
	echo ""
	gnome-terminal -e "airlight"
	sleep 1
	sudo airodump-ng -w out --encrypt wpa -c $ch --bssid $bssid $interface
elif [ $prog -eq 04 ] ;  then
	gnome-terminal -e "deauth.a"
	gnome-terminal -e "deauth.b"
	exit
elif [ $prog -eq 05 ] ; then
	sudo echo ""
	read -p "Dictionnaire Path : " dic
	read -p "Path du Fichier de Capture : " cap
	aircrack-ng -w /home/$USER/AirLight-master/dic/$dic /home/$USER/$cap
elif [ $prog -eq 06 ] ; then
	echo ""
	echo "      \033[1m                HELP                 \033[0m"
	echo ""
	echo "  Ce script a pour but de reunir les commandes"
	echo "  de la suite aircrack-ng."
	echo ""
	echo "  Si le programme bug durant le handshake c'est du a un probleme avec aircrack-ng, il suffit de redemarrer l'ordinateur, ou de reinstaller aircrack-ng..."
	echo "   Pour plus de détails :"
	echo ""
	read -p "  Souhaitez-vous relancer le programme ? [O/n] " ans
	if [ $ans = 'O' -o $ans = 'o' ] ; then
		ScriptLoc=$(readlink -f "$0")
		exec "$ScriptLoc"
	else
		exit
	fi
elif [ $prog -eq 07 ] ; then
	cd ~ && rm -rf aircrack-ng
	sudo apt-get remove --purge aircrack-ng -y
	sudo apt-get install libssl-dev -y && sudo apt-get install subversion -y
	sudo apt-get install build-essential autoconf automake libtool pkg-config libnl-3-dev libnl-genl-3-dev libssl-dev libsqlite3-dev libpcre3-dev ethtool shtool rfkill zlib1g-dev libpcap-dev -y
	sudo apt-get install aircrack-ng -y
	sudo apt install macchanger -y
	sudo apt update
	gnome-terminal -e "airlight"
elif [ $prog -eq 08 ] ; then
	exit
fi

